### ISSUE TITLE
Autoprimenet is double reporting results

### ISSUE THREAD

**Issue by jcoxdco** [primesearch/mfakto#10]
It seems that mfakto.ini and read_config.c are out of sync.

I have a clone of the latest code. When starting mfakto with the mfakto.ini included in source, read_config.c is reading (and if not found setting a default for) ResultsFile **and** JSONResultsFile

I think this is the reason that my most recent TF results were reported twice.

I'm happy to contribute a PR, but my question is... Is the intention to migrate to using the json results file?
I would imagine the behavior should be:
If JSONResultsFile is found in the .ini file, use it, otherwise use ResultsFile yeah?

**Comment by tdulcet** [comment]
mfakto writes the results in human readable format to a `results.txt` file and in JSON format to a `results.json.txt` file, but AutoPrimeNet only uses the JSON formatted results in the latter file.

Can you explain more about why you believe your results are being double reported? It might be helpful if you could provide the relevant section of your `autoprimenet.log` file for a result that was double reported.
